pipeline {   
    agent any 
    tools {
        maven 'M2_HOME'
        
    }
    stages {
        stage("SonarQube analysis") {          
            steps {
                withSonarQubeEnv('sonar') {
                    sh '''
                    mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonarQube \
                        -Dsonar.projectKey=Glory-Privilege_geo-app
                    '''
                }
            }
        }
        stage("Maven Build") {
            steps { 
                sh '''
                mvn clean
                mvn validate
                mvn compile 
                mvn install 
                mvn test
                mvn package
                '''
            }
        }
        stage('Upload Artifact') {
            steps {
                sh '''
                curl -uadmin:AP8gcgmmset5jeYChTJYDN6XmDd -T target/bio*.jar \
                "http://ec2-52-91-134-51.compute-1.amazonaws.com:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"
                '''
            }
        }
        stage('Docker Login') {
            steps {
                sh '''
                aws ecr get-login-password --region us-east-1 | \
                docker login --username AWS --password-stdin 076892551558.dkr.ecr.us-east-1.amazonaws.com
                '''
            }
        }
        stage('Docker Image Build') {
            steps {
                sh '''
                docker build -t utc-app-dev:v.${BUILD_ID} .
                docker build -t utc-app-dev:latest .
                '''
            }
        }
        stage('Image Tagging') {
            steps {
                sh '''
                docker tag utc-app-dev:v.${BUILD_ID} 076892551558.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:v.${BUILD_ID}
                docker tag utc-app-dev:latest 076892551558.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:latest
                '''
            }
        }
        stage('Push Image') {
            steps {  
                sh '''
                docker push 076892551558.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:latest
                docker push 076892551558.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:v.${BUILD_ID}
                '''
            }
        }
    }
}
